language: python

python:
  - 2.7

before_install:
  - pip install codecov

install:
#  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - nosetests -v --with-coverage --cover-inclusive

after_success:
  - codecov
